apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: "mysql-service"
  selector:
    matchLabels:
      db: mysql
  replicas: 1
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password
        volumeMounts:
        - name: persistent-storage-mysql
          mountPath: /var/lib/mysql
          
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage-mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: "standard"
