apiVersion: v1 
kind: Service 
metadata: 
  name: authentication-service
spec: 
  selector:
    app.k8s.io/name: authentication-weatherapp
  ports:  
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP